name: splitr
favicon: null
layout_spectrum: 1
typography_spectrum: 0.53831
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000f0c'
    - '#274253'
    - '#527289'
    - '#e1e2dd'
    - '#a6b4b7'
  brandStrength: 0.774738973705098
  lightness: 0.875
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
