name: splitr
favicon: null
layout_spectrum: 0.7235546759329736
typography_spectrum: 0.5026992957573384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#060606'
    - '#5f5742'
    - '#afb49e'
    - '#bf5732'
  brandStrength: 0.774738973705098
  lightness: 0.875
  saturation: 0.0625
  rhythmicContrast: 0.7462111823260784
purpose: []
